### ISSUE TITLE
shotnoise/relative_shotnoise stimulus is missing the reversal property

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/sonata-extension#18]
Similar to the [ornstein_uhlenbeck and relative_ornstein_uhlenbeck](https://sonata-extension.readthedocs.io/en/latest/sonata_simulation.html#ornstein-uhlenbeck-and-relative-ornstein-uhlenbeck-current-clamp-or-conductance) input, [shot_noise, absolute_shot_noise and relative_shot_noise (current_clamp or conductance)](https://sonata-extension.readthedocs.io/en/latest/sonata_simulation.html#shot-noise-absolute-shot-noise-and-relative-shot-noise-current-clamp-or-conductance) input can also be conductance clamp, therefore it uses the `reversal` property, no?

**Comment by mgeplf** [comment]
I think one of the simulator people need to answer that: @pramodk/@ferdonline/@WeinaJi/@jorblancoa ?
