### ISSUE TITLE
Using int, double, string and bool types in the metadata section

### ISSUE THREAD

**Issue by james-isbister** [BlueBrain/sonata-extension#26]
As discussed with Weina, it would be useful to be able to use int, double, string and bool types in the metadata section.

My reasoning was:
"With BlueConfigs I used to include simulation specific metadata that is not explicitly used by the simulator. I then use this data in my analyses. For example, the parameters of the population-specific Ornstein Uhlenbeck processes, which our current simulations use are determined when generating the simulation to attain target connected and unconnected firing rates for the different populations. I then use these firing rate values in my analysis so it is useful to keep them with the simulation specification. There are a number of other useful parameters like this that is useful to keep with the simulation config, as they are more interpretable than the raw OU parameters. So you can look back at the config and understand what the sim was"

**Comment by WeinaJi** [comment]
@james-isbister, could you please tell us when you need this feature? It will require a new release of `libsonata`. @mgeplf

**Comment by andrisecker** [comment]
@WeinaJi we need it ASAP, because we want to upload exemplary configs to the Zenodo repo linked to the SSCx physiology paper (the one where the MOD files will be).
