### ISSUE TITLE
node_sets_file resolution order

### ISSUE THREAD

**Issue by mgeplf** [BlueBrain/sonata-extension#29]
As @MWolfR pointed out, we should make sure we have the same resolution order of "node_sets_file"; the property that is defined in both the `circuit_config.json` and the `simulation_config.json`.

Currently, the wording is: `[...] and overriding the "node_sets_file" from the circuit configuration file which is specified by "network".` (https://github.com/BlueBrain/sonata-extension/blob/master/source/sonata_simulation.rst?plain=1#L58)

An alternative could be to:
1) Load the `circuit_config.json` version
2) Load the `simulation_config.json` version "overtop": ie: taking the union of both, with the `simulation_config.json` version taking precedence if there are key collisions.

**Comment by mgeplf** [comment]
Thoughts @MWolfR, @WeinaJi, @ferdonline, @GianlucaFicarelli, @joni-herttuainen, @pramodk, @jdcourcol  (feel free to forward to others)

**Comment by matz-e** [comment]
Having `simulation_config.json` add to the node sets seems to make me: I may want to define _additional_ node sets, while still having centrally defined ones available to me, and avoiding a copy of the information from the `circuit_config.json`.

Maybe this could come with a warning if node sets are shadowed?

**Comment by jdcourcol** [comment]
I agree with @matz-e 's proposal.

**Comment by mgeplf** [comment]
`add to the node sets seems to make me` do you mean `add to the node sets seems to make _sense_ me`? As in load it overtop, and also allow additional ones?

So, using libsonata as an example:
```
ns = libsonata.NodeSets.from_file('path/to/config_json defined NodeSets')
ns.add_from_file('path/to/simulation_json defined NodeSets', ignore_duplicate_names=True)
ns.add_from_json({'foo': {'mtype': 'bar'}}) # would throw if 'foo' already exists, otherwise merged in?
```

**Comment by joni-herttuainen** [comment]
I also think the proposition makes sense.

> Maybe this could come with a warning if node sets are shadowed?

Also agree on this one. If it doesn't overwrite, no warning. If it overwrites at least one, we could just have a general warning like `"Some node set rules were replaced"`. We for sure don't want warnings for each of them in case there are 100+ overwrites. 😅

**Comment by WeinaJi** [comment]
Hi, I agree with the proposition of warning. 

>Load the simulation_config.json version "overtop": ie: taking the union of both, with the simulation_config.json version taking precedence if there are key collisions.

Does it mean that the parser function `libsonata.SimulationConfig.node_sets_file` will return a list of node sets files (maybe 1 or 2 files)? If so, could the `libsonta.NodeSets` api provide a way to read the list of files? In such way, i think there is no much change on Neurodamus side.

**Comment by mgeplf** [comment]
Any feelings on the API I have above @joni-herttuainen, @WeinaJi, @matz-e?

**Comment by joni-herttuainen** [comment]
I think this is flexible enough and covers what is needed regarding SNAP.

**Comment by WeinaJi** [comment]
The API looks good. 
With the new `NodeSets.extend` function, I foresee that neurodamus will load NodeSets from both `Circuit_config.node_sets_path` and `SimulationConfig.node_sets_file`, and then `extend`. 
@jorblancoa @ferdonline ,  what do you think of the change?

**Comment by matz-e** [comment]
Seems fine. I'd like to point out that Python's `dict` uses `update` for very similar functionality

**Comment by mgeplf** [comment]
@matz-e > Seems fine. I'd like to point out that Python's dict uses update for very similar functionality

Are you thinking more along the lines:
```
ns0 = libsonata.NodeSets.from_file('path/to/config_json defined NodeSets')
ns1 = libsonata.NodeSets.from_file('....')
ns0.update(ns1)
```
I'm pretty sure I thought about that, but now I forget why I discounted it.

**Comment by matz-e** [comment]
Yes, that's what I was thinking of. No hard requirement, though.

**Comment by markovg** [comment]
@mgeplf late to the party. Just like to add my +1 i.e. like the direction this is going, i.e. alternative #2 with warnings. I'm faced with copying over node_sets from circuit/node_sets.json to simulation/node_sets.json atm, and I think the proposal is much cleaner ... start.target worked like this back in the day ... i.e. the circuit could define "base" targets/node_sets that could then be augmented by the user ...

**Comment by mgeplf** [comment]
I made the change to https://github.com/BlueBrain/libsonata/pull/283.  @WeinaJi can you try it and see if it makes sense for you?

**Comment by WeinaJi** [comment]
> I made the change to [BlueBrain/libsonata#283](https://github.com/BlueBrain/libsonata/pull/283). @WeinaJi can you try it and see if it makes sense for you?

I've tried and it looks good. I will modify the SONATA spec and implement it in `neurodamus`.

**Comment by mgeplf** [comment]
I have added to the SONATA spec here:
https://github.com/BlueBrain/sonata-extension/pull/33

Once that's in, we'll tag libsonata and update SNAP.

**Comment by mgeplf** [comment]
The above is merged, now we can implement it in other places.  Thanks everyone.
