### ISSUE TITLE
data type of spike_threshold being int instead of float

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/sonata-extension#42]
Hi, 

the underlying NEURON NetCon object represents the threshold parameter as a double. 
https://github.com/neuronsimulator/nrn/blob/f71c64e2a0e56aa628a6196bc9110937ad91c47e/src/coreneuron/network/netcon.hpp#L110

Python usage:
https://github.com/ModelDBRepository/225080/blob/65d1d97bb2f1dcc61ab223214b3eb9a529cb282c/specify_cells.py#L619C50-L619C50

The blueconfig format was also representing it as a float point number type.
The SONATA spec however uses integer. Shouldn't it be using float instead?

cc @edasubert

**Comment by mgeplf** [comment]
That does seem strange.
Perhaps @jamesgking can comment on why integer was chosen?

**Comment by mgeplf** [comment]
Any chance to look at this @jamesgking? Can you assign someone else to have a look?  I'd like to get this corrected in case we want to include it in a libsonata release.

**Comment by mgeplf** [comment]
Could you assign someone @jamesgking? Maybe @WeinaJi or @ferdonline know?

**Comment by WeinaJi** [comment]
Yes, it should be float. Thank @anilbey for spotting that. I will make the change in the SONATA spec and the libsonata API.  There is no change needed on the neurodamus side.
